User.create(name: 'Marcos' ,email: 'marcos@teste.com' ,password: '123456',password_confirmation: '123456' , alias: 'Marcos',registration: '55329')
User.create(name: 'Josinaldo' ,email: 'josinaldo@teste.com',password: '123456',password_confirmation: '123456', alias: 'Josinaldo' ,registration: '55330')
User.create(name: 'Loiola' ,email: 'loiola@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Loiola',registration: '55331')
User.create(name: 'Vieira',email: 'vieira@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Vieira' ,registration: '55332')
User.create(name: 'Eliomar',email: 'eliomar@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Eliomar' ,registration: '55333', supervisor: false)
User.create(name: 'Edilberto',email: 'edilberto@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Edilberto' ,registration: '55334', admin: false)
User.create(name: 'Walber',email: 'walber@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Walber' ,registration: '12420', admin: true)
User.create(name: 'Daniel',email: 'daniel@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Daniel' ,registration: '13948', supervisor: true)
User.create(name: 'Joheldes',email: 'joheldes@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Joheldes' ,registration: '15298', supervisor: true)
User.create(name: 'Tárcila',email: 'tarcila@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Tárcila' ,registration: '39877', supervisor: true)
User.create(name: 'Aguiar',email: 'aguiar@teste.com' ,password: '123456',password_confirmation: '123456', alias: 'Walber' ,registration: '12415', supervisor: true)
User.create(name: 'Jafer Daltro Pompeu Jr',email: 'jaferjr@gmail.com' ,password: '123456',password_confirmation: '123456', alias: 'Daltro' ,registration: '39864', admin: true)

Car.create(owner: 'AMT', kind: 'pickup_truck', licence_plate: 'OZA-9831' ,vtr: '01',brand: 'Volkswagem' ,model: 'Amarok' ,mileage: 0,busy: false ,status: 'unready' ,fuel: 'diesel' ,operation: 'operation')
Car.create(owner: 'AMT', kind: 'hatch', licence_plate: 'PMT-4182' ,vtr: '07', brand: 'Volkswagem' ,model: 'GOL' ,mileage: 0,busy: false,status: 'unready' ,fuel: 'flex' ,operation: 'operation')
Car.create(owner: 'AMT', kind: 'hatch', licence_plate: 'PMT-4232' ,vtr: '08', brand: 'Volkswagem' ,model: 'GOL' ,mileage: 0,busy: false,status: 'unready' ,fuel: 'flex' ,operation: 'operation')
Car.create(owner: 'AMT', kind: 'hatch', licence_plate: 'PMT-4192' ,vtr: '09', brand: 'Volkswagem' ,model: 'GOL' ,mileage: 0,busy: false,status: 'unready' ,fuel: 'flex' ,operation: 'operation')
